organizations/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('organizations.views',
    (r'^$', 'index'),
    (r'^(?P<organization_id>\d+)/$', 'detail'),
    (r'^staff/(?P<person_id>\d+)/$', 'people_detail')
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'noi_test.views.home', name='home'),
    # url(r'^noi_test/', include('noi_test.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^$', include('organizations.urls')),
    (r'^orgs/', include('organizations.urls')),
    # Uncomment the next line to enable the admin:
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

organizations/models.py
from django.db import models

# Create your models here.
class Organization(models.Model):
    name = models.CharField(max_length=200)
    founded_date = models.DateField()
    legal_status = models.CharField(max_length=50)
    number_staff = models.IntegerField('number of staff')
    contact_person = models.ForeignKey('Person', related_name='+', null=True, blank=True)
    
    def __unicode__(self):
            return self.name
            
class Person(models.Model):
    ENUM_CHOICES = (
        (u'Y', u'Yes'),
        (u'N', u'No'),
    )
    organization = models.ForeignKey(Organization)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    attended_trainings = models.CharField(max_length=2, choices=ENUM_CHOICES)
    electoral_experience = models.CharField(max_length=2, choices=ENUM_CHOICES)
    active_projects = models.CharField(max_length=255)
    
    def __unicode__(self):
            return self.name
    
class Internal(models.Model):
    ENUM_CHOICES = (
        (u'Y', u'Yes'),
        (u'N', u'No'),
    )
    
    RELATIONSHIP_CHOICES = (
        (u'Da', u'Dating'),
        (u'Di', u'Divorced'),
        (u'Ma', u'Married'),
        (u'Si', u'Single'),        
    )    
    
    ACTIVITY_CHOICES = (
        (u'Pro', u'Proactive'),
        (u'Re', u'Reactive'),
    )
    
    organization = models.ForeignKey(Organization, unique=True)
    relationship_status = models.CharField(max_length=4, choices=RELATIONSHIP_CHOICES)
    familiarity = models.CharField(max_length=2, choices=ENUM_CHOICES)
    action_steps = models.TextField()
    activity_level = models.CharField(max_length=4, choices=ACTIVITY_CHOICES)
    
    def __unicode__(self):
            return self.organization.name

organizations/views.py
from organizations.models import Organization
from organizations.models import Person
from django.shortcuts import render_to_response, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    org_list = Organization.objects.all()
    paginator = Paginator(org_list, 15)
    page = request.GET.get('page')
    try:
        orgs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        orgs = paginator.page(1)
    except TypeError:
        # If page is not an integer, deliver first page.
        orgs = paginator.page(1)        
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        orgs = paginator.page(paginator.num_pages)
    return render_to_response('organizations/index.html', {'orgs': orgs})
    
def detail(request, organization_id):
    org = get_object_or_404(Organization, pk=organization_id)
    return render_to_response('organizations/detail.html', {'org': org})

def people_detail(request, person_id):
    p = get_object_or_404(Person, pk=person_id)
    return render_to_response('organizations/person_detail.html', {'person': p})

templates/admin_doc/bookmarklets.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block bodyclass %}documentation{% endblock %}
{% block content-class %}content-grid{% endblock %}
{% block breadcrumbs %}{% load i18n %}<div id="breadcrumbs"><a href="../../">{% trans "Home" %}</a> &rsaquo; <a href="../">{% trans "Documentation" %}</a> &rsaquo; {% trans "Bookmarklets" %}</div>{% endblock %}
{% block title %}{% trans "Documentation bookmarklets" %}{% endblock %}

{% block content %}
    <h1>{% trans "Bookmarklets" %}</h1>
    <div class="container-grid rte">
        {% blocktrans %}
            <p>To install bookmarklets, drag the link to your bookmarks
    toolbar, or right-click the link and add it to your bookmarks. Now you can
    select the bookmarklet from any page in the site.  Note that some of these
    bookmarklets require you to be viewing the site from a computer designated
    as "internal" (talk to your system administrator if you aren't sure if
    your computer is "internal").</p>
        {% endblocktrans %}
        <div class="module">
            <h2><a href="javascript:(function(){if(typeof ActiveXObject!='undefined'){x=new ActiveXObject('Microsoft.XMLHTTP')}else if(typeof XMLHttpRequest!='undefined'){x=new XMLHttpRequest()}else{return;}x.open('HEAD',location.href,false);x.send(null);try{view=x.getResponseHeader('x-view');}catch(e){alert('No view found for this page');return;}if(view=='undefined'){alert('No view found for this page');}document.location='{{ admin_url }}doc/views/'+view+'/';})()">{% trans "Documentation for this page" %}</a></h2>
            <p>{% trans "Jumps you from any page to the documentation for the view that generates that page." %}</p>
        </div>
        <div class="module">
            <h2><a href="javascript:(function(){if(typeof ActiveXObject!='undefined'){x=new ActiveXObject('Microsoft.XMLHTTP')}else if(typeof XMLHttpRequest!='undefined'){x=new XMLHttpRequest()}else{return;}x.open('GET',location.href,false);x.send(null);try{type=x.getResponseHeader('x-object-type');id=x.getResponseHeader('x-object-id');}catch(e){type='(none)';id='(none)';}d=document;b=d.body;e=d.createElement('div');e.id='xxxhhh';s=e.style;s.position='absolute';s.left='10px';s.top='10px';s.font='10px monospace';s.border='1px black solid';s.padding='4px';s.backgroundColor='#eee';e.appendChild(d.createTextNode('Type: '+type));e.appendChild(d.createElement('br'));e.appendChild(d.createTextNode('ID: '+id));e.appendChild(d.createElement('br'));l=d.createElement('a');l.href='#';l.onclick=function(){b.removeChild(e);};l.appendChild(d.createTextNode('[close]'));l.style.textDecoration='none';e.appendChild(l);b.appendChild(e);})();">{% trans "Show object ID" %}</a></h2>
            <p>{% trans "Shows the content-type and unique ID for pages that represent a single object." %}</p>
        </div>
        <div class="module">
            <h2><a href="javascript:(function(){if(typeof ActiveXObject!='undefined'){var x=new ActiveXObject('Microsoft.XMLHTTP')}else if(typeof XMLHttpRequest!='undefined'){var x=new XMLHttpRequest()}else{return;}x.open('GET',location.href,false);x.send(null);try{var type=x.getResponseHeader('x-object-type');var id=x.getResponseHeader('x-object-id');}catch(e){return;}document.location='{{ admin_url }}'+type.split('.').join('/')+'/'+id+'/';})()">{% trans "Edit this object (current window)" %}</a></h2>
            <p>{% trans "Jumps to the admin page for pages that represent a single object." %}</p>
        </div>
        <div class="module">
            <h2><a href="javascript:(function(){if(typeof ActiveXObject!='undefined'){var x=new ActiveXObject('Microsoft.XMLHTTP')}else if(typeof XMLHttpRequest!='undefined'){var x=new XMLHttpRequest()}else{return;}x.open('GET',location.href,false);x.send(null);try{var type=x.getResponseHeader('x-object-type');var id=x.getResponseHeader('x-object-id');}catch(e){return;}window.open('{{ admin_url }}'+type.split('.').join('/')+'/'+id+'/');})()">{% trans "Edit this object (new window)" %}</a></h2>
            <p>{% trans "As above, but opens the admin page in a new window." %}</p>
        </div>
    </div>
{% endblock %}

templates/admin_doc/index.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block bodyclass %}documentation{% endblock %}
{% block content-class %}content-grid{% endblock %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="{{ root_path }}">Home</a> &rsaquo; Documentation</div>{% endblock %}
{% block title %}Documentation{% endblock %}

{% block content %}
    <h1>Documentation</h1>
    <div class="container-grid rte">
        <div class="module">
            <h2><a href="tags/">Tags</a></h2>
            <p>List of all the template tags and their functions.</p>
        </div>
        <div class="module">
            <h2><a href="filters/">Filters</a></h2>
            <p>Filters are actions which can be applied to variables in a template to alter the output.</p>
        </div>
        <div class="module">
            <h2><a href="models/">Models</a></h2>
            <p>Models are descriptions of all the objects in the system and their associated fields. Each model has a list of fields which can be accessed as template variables.</p>
        </div>
        <div class="module">
            <h2><a href="views/">Views</a></h2>
            <p>Each page on the public site is generated by a view. The view defines which template is used to generate the page and which objects are available to that template.</p>
        </div>
        <div class="module">
            <h2><a href="bookmarklets/">Bookmarklets</a></h2>
            <p>Tools for your browser to quickly access admin functionality.</p>
        </div>
    </div>
{% endblock %}

templates/admin_doc/missing_docutils.html
{% extends "admin/_grappelli/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block bodyclass %}documentation{% endblock %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="../">Home</a> &rsaquo; Documentation</div>{% endblock %}
{% block title %}Please install docutils{% endblock %}

{% block content %}
    <h1>Documentation</h1>
    <div id="content-main">
        <h3>The admin documentation system requires Python's <a href="http://docutils.sf.net/">docutils</a> library.</h3>
        <p>Please ask your administrators to install <a href="http://docutils.sf.net/">docutils</a>.</p>
    </div>
{% endblock %}

templates/admin_doc/model_detail.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript">
        (function($) {
            $(document).ready(function(){
                $('.rte .module').each(function(){
                    var childWidth = $('.rte .module').children("table").outerWidth();
                    $('.rte .module').css("width", childWidth);
                });
            });
        })(django.jQuery);
    </script>
{% endblock %}
{% block bodyclass %}documentation{% endblock %}
{% block content-class %}content-grid{% endblock %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="../../../">Home</a> &rsaquo; <a href="../../">Documentation</a> &rsaquo; <a href="../">Models</a> &rsaquo; {{ name }}</div>{% endblock %}

{% block title %}Model: {{ name }}{% endblock %}

{% block content %}
    <h1>{{ summary }}</h1>
    <div class="container-grid rte">
        {% if description %}
            <p>{% filter linebreaksbr %}{% trans description %}{% endfilter %}</p>
        {% endif %}
        <div class="module model">
            <table class="model" style="width: auto">
                <thead>
                    <tr>
                        <th>Field</th>
                        <th>Type</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for field in fields|dictsort:"name" %}
                        <tr>
                            <td class="nowrap focus">{{ field.name }}</td>
                            <td class="nowrap">{{ field.data_type }}</td>
                            <td>{{ field.verbose }}{% if field.help_text %} - {{ field.help_text|safe }}{% endif %}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="../" class="back">&lsaquo; Back to Models Documentation</a>
    </div>
{% endblock %}

templates/admin_doc/model_index.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% admin_media_prefix %}js/documentation.js"></script>
{% endblock %}

{% block bodyclass %}documentation model-index{% endblock %}
{% block content-class %}content-grid{% endblock %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="../../">Home</a> &rsaquo; <a href="../">Documentation</a> &rsaquo; Models</div>{% endblock %}

{% block title %}Models{% endblock %}

{% block content %}
    <h1>Model documentation</h1>
    {% regroup models by app_label as grouped_models %}
    <div class="container-grid">
        <div class="column span-6">
            <div class="module table-of-contents">
                <h2>Model groups</h2>
                <ul>
                    {% regroup models by app_label as grouped_models %}
                    {% for group in grouped_models %}
                        <li><a href="#app-{{ group.grouper }}">{{ group.grouper|capfirst }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="column span-18 last rte">
            {% for group in grouped_models %}
                <div class="module">
                    <h2 id="app-{{ group.grouper }}">{{ group.grouper|capfirst }}</h2>
                    <table>
                        {% for model in group.list %}
                            <tr>
                                <th><a href="{{ model.app_label }}.{{ model.object_name.lower }}/">{{ model.object_name }}</a></th>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/admin_doc/template_detail.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block bodyclass %}documentation{% endblock %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="../../../">Home</a> &rsaquo; <a href="../../">Documentation</a> &rsaquo; Templates &rsaquo; {{ name }}</div>{% endblock %}

{% block title %}Template: {{ name }}{% endblock %}

{% block content %}
    <h1>Template: "{{ name }}"</h1>
    {% regroup templates|dictsort:"site_id" by site as templates_by_site %}
    {% for group in templates_by_site %}
        <h2>Search path for template "{{ name }}" on {{ group.grouper }}:</h2>
        <ol>
            {% for template in group.list|dictsort:"order" %}
                <li><code>{{ template.file }}</code>{% if not template.exists %} <em>(does not exist)</em>{% endif %}</li>
            {% endfor %}
        </ol>
    {% endfor %}
    <p class="small"><a href="../../">&lsaquo; Back to Documentation</a></p>
{% endblock %}

templates/admin_doc/template_filter_index.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% admin_media_prefix %}js/documentation.js"></script>
{% endblock %}
{% block bodyclass %}documentation{% endblock %}
{% block content-class %}content-grid{% endblock %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="../../">Home</a> &rsaquo; <a href="../">Documentation</a> &rsaquo; filters</div>{% endblock %}
{% block title %}Template filters{% endblock %}

{% block content %}
    <h1>Template filter documentation</h1>
    <div class="container-grid">
        <div class="column span-6">
            {% regroup filters|dictsort:"library" by library as filter_libraries %}
            {% for library in filter_libraries %}
                <div class="module table-of-contents">
                    <h2>{% firstof library.grouper "Built-in filters" %}</h2>
                    <ul>
                        {% for filter in library.list|dictsort:"name" %}
                            <li><a href="#{{ filter.name }}">{{ filter.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
        <div class="column span-18 last rte">
            {% regroup filters|dictsort:"library" by library as filter_libraries %}
            {% for library in filter_libraries %}
                <div class="group collapsible open">
                    <h2 class="collapsible-handler">{% firstof library.grouper "Built-in filters" %}</h2>
                    {% if library.grouper %}<p>To use these filters, put <code>{% templatetag openblock %} load {{ library.grouper }} {% templatetag closeblock %}</code> in your template before using the filter.</p>{% endif %}
                    {% for filter in library.list|dictsort:"name" %}
                        <div class="module">
                            <h3 id="{{ filter.name }}">{{ filter.name }}</h3>
                            <p>{{ filter.title }}</p>
                            <p>{{ filter.body }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/admin_doc/template_tag_index.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% admin_media_prefix %}js/documentation.js"></script>
{% endblock %}
{% block bodyclass %}documentation{% endblock %}
{% block content-class %}content-grid{% endblock %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="../../">Home</a> &rsaquo; <a href="../">Documentation</a> &rsaquo; Tags</div>{% endblock %}
{% block title %}Template tags{% endblock %}

{% block content %}
    <h1>Template tag documentation</h1>
    <div class="container-grid">
        <div class="column span-6">
            {% regroup tags|dictsort:"library" by library as tag_libraries %}
            {% for library in tag_libraries %}
                <div class="module table-of-contents">
                    <h2>{% firstof library.grouper "Built-in tags" %}</h2>
                    <ul>
                        {% for tag in library.list|dictsort:"name" %}
                            <li><a href="#{{ tag.name }}">{{ tag.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
        <div class="column span-18 last rte">
            {% regroup tags|dictsort:"library" by library as tag_libraries %}
            {% for library in tag_libraries %}
                <div class="group collapsible open">
                    <h2 class="collapsible-handler">{% firstof library.grouper "Built-in tags" %}</h2>
                    {% if library.grouper %}<p class="small quiet">To use these tags, put <code>{% templatetag openblock %} load {{ library.grouper }} {% templatetag closeblock %}</code> in your template before using the tag.</p>{% endif %}
                    {% for tag in library.list|dictsort:"name" %}
                        <div class="module">
                            <h3 id="{{ tag.name }}">{{ tag.name }}</h3>
                            <h4>{{ tag.title }}</h4>
                            <p>{{ tag.body }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/admin_doc/view_detail.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block bodyclass %}documentation{% endblock %}
{% block content-class %}content-grid{% endblock %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="../../../">Home</a> &rsaquo; <a href="../../">Documentation</a> &rsaquo; <a href="../">Views</a> &rsaquo; {{ name }}</div>{% endblock %}
{% block title %}View: {{ name }}{% endblock %}

{% block content %}
    <h1>{{ name }}</h1>
    <div class="container-grid rte">
        <div class="module">
            <h2>{{ summary }}</h2>
            <p>{{ body }}</p>
            {% if meta.Context %}
                <div class="module">
                    <h3>Context:</h3>
                    <p>{{ meta.Context }}</p>
                </div>
            {% endif %}
            {% if meta.Templates %}
                <div class="module">
                    <h3>Templates:</h3>
                    <p>{{ meta.Templates }}</p>
                </div>
            {% endif %}
        </div>
        <a href="../" class="back">&lsaquo; Back to Views Documentation</a>
    </div>
{% endblock %}

templates/admin_doc/view_index.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}
{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% admin_media_prefix %}js/documentation.js"></script>
{% endblock %}
{% block bodyclass %}documentation{% endblock %}
{% block content-class %}content-grid{% endblock %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="../../">Home</a> &rsaquo; <a href="../">Documentation</a> &rsaquo; Views</div>{% endblock %}
{% block title %}Views{% endblock %}

{% block content %}
    <h1>View documentation</h1>
    {% regroup views|dictsort:"site_id" by site as views_by_site %}
    <div class="container-grid">
        <div class="column span-6">
            <div class="module table-of-contents">
                <h2>Jump to site</h2>
                <ul>
                    {% for site_views in views_by_site %}
                        <li><a href="#site{{ site_views.grouper.id }}">{{ site_views.grouper.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="column span-18 last rte">
            {% for site_views in views_by_site %}
                <div class="group">
                    <h2 id="site{{ site_views.grouper.id }}">Views by URL on {{ site_views.grouper.name }}</h2>
                    {% for view in site_views.list|dictsort:"url" %}
                        {% ifchanged %}
                            <div class="module">
                                <h3><a href="{{ view.module }}.{{ view.name }}/">{{ view.url }}</a></h3>
                                <p class="small quiet">View function: {{ view.module }}.{{ view.name }}</p>
                                <p>{{ view.title }}</p>
                            </div>
                        {% endifchanged %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/organizations/base.html
<!doctype html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	<title>NOI Organization Tracker</title>
	<meta name="description" content="">
	<meta name="author" content="">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="shortcut icon" href="/static/img/favicon.ico">
	<link rel="apple-touch-icon" href="/static/img/apple-touch-icon.png">
	<link rel="stylesheet" href="/static/css/style.css">
	<link rel="stylesheet" media="handheld" href="/static/css/handheld.css">
	<script src="/static/js/libs/modernizr-1.7.min.js"></script>
	<script type="text/javascript" src="http://use.typekit.com/bbl7wft.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body>
	<div id="container">
		<nav>
			<div id="userbar">
					<a href="/admin">Admin</a>
			</div>
		</nav>
		<header>
			<h1><a href="/">NOI Organization Tracker</a></h1>
		</header>
		{% block content %}
			{{ content }}
		{% endblock %}
		<footer>

		</footer>
	</div>

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
	<script>!window.jQuery && document.write(unescape('%3Cscript src="js/libs/jquery-1.5.1.min.js"%3E%3C/script%3E'))</script>
	<script src="js/plugins.js"></script>
	<script src="js/script.js"></script>
	<!--[if lt IE 7 ]>
	<script src="js/libs/dd_belatedpng.js"></script>
	<script> DD_belatedPNG.fix('img, .png_bg');</script>
	<![endif]-->
	<script>
		var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
		(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
		g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
		s.parentNode.insertBefore(g,s)}(document,'script'));
	</script>
</body>
</html>

templates/organizations/detail.html
{% extends "organizations/base.html" %}

{% block content %}
<div id="main">
	<div id="display">
		<ul>
			<li class="title">Organization</li>
			<li>Name: {{ org.name }}</li>
			<li>Founded: {{ org.founded_date }}</li>
			<li>Type: {{ org.legal_status }}</li>
			<li>Staff Size: {{ org.number_staff }}</li>
			<li>Contact Person: <a href="/orgs/staff/{{ org.contact_person.id }}">{{ org.contact_person.name }}</a></li>
			<li class="title">Other Staff</li>
			{% for person in org.person_set.all %}
				{% if org.contact_person.id != person.id %}
					<li>Name: <a href="/orgs/staff/{{ person.id }}">{{ person.name }}</a></li>
				{% else %}
					<li>No other staff listed for organization</li>
				{% endif %}
			{% endfor %}
			<li><a href="/"><input type="button" class="home" value="Home"></a></li>
		</ul>
	</div>
</div>
{% endblock %}

templates/organizations/index.html
{% extends "organizations/base.html" %}
{% block content %}
<div id="main" role="main">
	{% if orgs %}
		<table id="list" cellspacing="0">
			<thead>
				<tr>
					<th>Organization Name</th>
					<th>Founded Date</th>
					<th>Type</th>
					<th>Staff Size</th>
					<th>Contact Person</th>		
				</tr>
			</thead>
			<tbody>
				{% for org in orgs.object_list %}
				<tr>
        	<td><a href="/orgs/{{ org.id }}/">{{ org.name }}</a></td>
					<td>{{ org.founded_date }}</td>
					<td>{{ org.legal_status }}</td>
					<td>{{ org.number_staff }}</td>
					<td><a href="/orgs/staff/{{ org.contact_person.id }}">{{ org.contact_person.name }}</a></td>
				</tr>
    		{% endfor %}
				<tr>
					<td colspan="5">
						<div class="pagination">
						    <span class="step-links">
						        {% if orgs.has_previous %}
						            <a href="?page={{ orgs.previous_page_number }}">previous</a>
						        {% endif %}

						        <span class="current">
						            Page {{ orgs.number }} of {{ orgs.paginator.num_pages }}.
						        </span>

						        {% if orgs.has_next %}
						            <a href="?page={{ orgs.next_page_number }}">next</a>
						        {% endif %}
						    </span>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	{% else %}
		<p>No organizations listed. Would you like to <a href="/admin">add</a> some?</p>
	{% endif %}
</div>
{% endblock %}

templates/organizations/person_detail.html
{% extends "organizations/base.html" %}
{% block content %}
<div id="main">
	<div id="display">
		<ul>
			<li class="title">Staff Member</li>
			<li>Name: {{ person.name }}</li>
			<li>Organization: <a href="/orgs/{{ person.organization.id }}">{{ person.organization.name }}</a></li>
			<li>Email: {{ person.email }}</li>
			<li>Phone #: {{ person.phone }}</li>
			<li>Attended Training?: {{ person.attended_trainings }}</li>
			<li>Electoral Experience?: {{ person.electoral_experience }}</li>
			<li>Active Projects: {{ person.active_projects }}</li>
			<li><a href="/"><input type="button" class="home" value="Home"></a></li>
		</ul>
	</div>
</div>
{% endblock %}